SSoelvsten/adiar

src/coom/bdd/bdd.h
src/coom/bdd/count.cpp
src/coom/bdd/count.h
src/coom/file.cpp
src/coom/file.h
test/coom/bdd/test_count.cpp

Add bdd_varcount and don't count sink nodes in bdd_nodecount

---

src/coom/bdd/apply.cpp
src/coom/bdd/bdd.h
test/coom/bdd/test_apply.cpp

Add O(1) manipulation of the same BDD given twice to Apply

---

src/coom/bdd/quantify.cpp
test/coom/bdd/test_quantify.cpp

Fix missing sink-sink case in quantification algorithm

---

.github/codecov.yml
README.md

More CodeCov.io setup

---

docs/_config.yml

- Remove some 'dead code' in the settings
- Set it to 'dark' mode instead.

Minor changes for documentation settings

---

AUTHORS.md
CITE.md
README.md
docs/cite.md
docs/index.md

I will merge this tomorrow, when I get the final verdict from TACAS.

Add guide for citation and improve credits

---

docs/bdd.md
docs/zdd.md
src/adiar/CMakeLists.txt
src/adiar/adiar.h
src/adiar/bdd/evaluate.cpp
src/adiar/bdd/evaluate.h
src/adiar/zdd/contains.cpp
src/adiar/zdd/contains.h
test/adiar/bdd/test_evaluate.cpp
test/adiar/zdd/test_contains.cpp
test/test.cpp

Closes #185 . I thought to use the policy pattern again, but the added complexity is really not worth it for such a "simple" function.

Feature: zdd_contains

---

docs/zdd.md
src/adiar/CMakeLists.txt
src/adiar/adiar.h
src/adiar/file_writer.h
src/adiar/internal/intercut.h
src/adiar/zdd/change.cpp
src/adiar/zdd/change.h
src/adiar/zdd/expand.cpp
src/adiar/zdd/expand.h
test/adiar/zdd/test_expand.cpp
test/test.cpp

Adds the `zdd_expand` function as a generalisation of the algorithm for `zdd_change`.

Feature: zdd_expand

---

src/adiar/CMakeLists.txt
src/adiar/adiar.h
src/adiar/internal/build.h
src/adiar/internal/intercut.h
src/adiar/zdd/change.cpp
src/adiar/zdd/complement.cpp
src/adiar/zdd/complement.h
src/adiar/zdd/expand.cpp
test/adiar/zdd/test_binop.cpp
test/adiar/zdd/test_change.cpp
test/adiar/zdd/test_complement.cpp
test/test.cpp

Adds `zdd_complement` ( closes #183 ) and also fixes bad handling of skipping the root in `zdd_change`.

Feature: zdd_complement

---

CHANGELOG.md
CMakeLists.txt
LICENSE.md
docs/bdd.md
docs/cite.md
docs/core.md
docs/core/data_types.md
docs/core/files.md
docs/examples.md
docs/examples/queens.md
docs/getting_started.md
docs/index.md
docs/statistics.md
docs/zdd.md

Proof read and update documentation for release of _v1.1.0_

Relase v1.1.0 !

---

.github/workflows/examples.yml

Fix Knight's Tour cannot be made required on Pull Requests

---

test/adiar/internal/test_reduce.cpp

Add a unit test for two Reduction 1 rule applications on the same level

---

makefile
test/test.cpp

Change settings for make test to those for make main and add printing statistics after tests

---

src/adiar/internal/sorter.h

Decrease memory in phase 1 to circumvent wasteful allocations

---

src/adiar/statistics.cpp

Add a warning when calling adiar_stats without flag ADIAR_STATS

---

src/adiar/internal/sorter.h

Allow internal_sorter to reuse an allocation

---

src/adiar/bdd/if_then_else.cpp
src/adiar/internal/decision_diagram.h
src/adiar/internal/intercut.h
src/adiar/internal/levelized_priority_queue.h
src/adiar/internal/pred.h
src/adiar/internal/product_construction.h

Internal memory product construction

---

src/adiar/bdd/count.cpp
src/adiar/internal/count.h
src/adiar/internal/decision_diagram.h
src/adiar/internal/product_construction.h
src/adiar/internal/reduce.h
src/adiar/zdd/count.cpp

One more step on the way through #98

Internal memory/count

---

src/adiar/bdd/if_then_else.cpp
src/adiar/internal/decision_diagram.h

Use internal memory in if_then_else when possible

---

src/adiar/internal/decision_diagram.h
src/adiar/internal/product_construction.h
src/adiar/internal/quantify.h

Use internal memory when possible in quantify

---

src/adiar/internal/decision_diagram.h
src/adiar/internal/intercut.h
src/adiar/internal/levelized_priority_queue.h

How big is #98 anyway? It just keeps going

Use internal memory in intercut when possible

---

src/adiar/internal/levelized_priority_queue.h
src/adiar/internal/sorter.h

Improve performance by reusing allocations of prior sorters

---

src/adiar/bdd/pred.cpp
src/adiar/internal/pred.cpp
src/adiar/internal/pred.h
src/adiar/zdd/pred.cpp

Use internal memory in comparison check when possible

---

src/adiar/bdd/if_then_else.cpp
test/adiar/bdd/test_if_then_else.cpp

Closes #295 
Also refactors the if_then_else test file to group similar tests together

Fix zipping in if_then_else to not zip when else-branch is not below conditional

---

src/adiar/CMakeLists.txt
src/adiar/bdd/if_then_else.cpp
src/adiar/bdd/if_then_else.h
src/adiar/internal/count.cpp
src/adiar/internal/count.h
src/adiar/internal/intercut.cpp
src/adiar/internal/intercut.h
src/adiar/internal/pred.h
src/adiar/internal/product_construction.cpp
src/adiar/internal/product_construction.h
src/adiar/internal/quantify.cpp
src/adiar/internal/quantify.h
src/adiar/internal/reduce.h
src/adiar/internal/substitution.cpp
src/adiar/internal/substitution.h
src/adiar/statistics.cpp
src/adiar/statistics.h

Add statistics for type of auxilliary data structures

---

src/adiar/bdd/if_then_else.cpp
src/adiar/internal/intercut.h
src/adiar/internal/product_construction.h
src/adiar/internal/quantify.h
src/adiar/internal/substitution.h
src/adiar/internal/util.h
src/adiar/zdd/pred.cpp

Make sure size_bound computations do not overflow and cause wrong choice of auxilliary data structures

---

.github/workflows/system_test.yml
test/adiar/internal/test_reduce.cpp

Fix Reduce statistics are not gathered in unit tests

---

src/adiar/bdd/if_then_else.cpp
test/adiar/bdd/test_if_then_else.cpp

Approximate 1- and 2-level cuts when zipping BDDs in if_then_else

---

.github/workflows/system_test.yml
src/adiar/bdd/bdd_policy.h
src/adiar/internal/reduce.h
test/adiar/internal/test_reduce.cpp

Fix chain of reduction rule 1 may increase cut

---

src/adiar/bdd/bdd.cpp
src/adiar/bdd/bdd.h
src/adiar/file.h
src/adiar/internal/dot.h
src/adiar/zdd/zdd.h

Change output_dot to use Ø and {Ø} for sinks in ZDDs

---

src/adiar/CMakeLists.txt
src/adiar/adiar.h
src/adiar/builder.h
src/adiar/file_writer.h
test/adiar/test_builder.cpp
test/test.cpp

Create builder for BDDs and ZDDs

---

src/adiar/bdd/if_then_else.cpp
src/adiar/internal/convert.h
src/adiar/internal/count.h
src/adiar/internal/intercut.h
src/adiar/internal/levelized_priority_queue.h
src/adiar/internal/pred.cpp
src/adiar/internal/pred.h
src/adiar/internal/priority_queue.h
src/adiar/internal/product_construction.h
src/adiar/internal/quantify.h
src/adiar/internal/reduce.h
src/adiar/internal/substitution.h
src/adiar/statistics.cpp
src/adiar/statistics.h
src/adiar/zdd/change.cpp
src/adiar/zdd/complement.cpp
src/adiar/zdd/expand.cpp
src/adiar/zdd/pred.cpp
test/adiar/internal/test_levelized_priority_queue.cpp

Closes #149 and also closes #363

Unbucketed levelized priority queue

---

src/adiar/statistics.cpp
src/adiar/statistics.h

Fix statistics are not reported if only run unbucketed

---

.github/workflows/benchmark.py

Make benchmark.py error on non-compilation

---

CONTRIBUTING.md

Inspired by Magnus Madsen's Design Principles, it might be good to begin writing some down to the design of Adiar too as a guide for future contributors.

Add CONTRIBUTING.md with Git Flow and Design Principles

---

src/adiar/internal/io/levelized_file.h

Hi 
This is my first contribution to open source, thank you for the opportunity.
i have changed _canonical variable name in levelized_file.h to _canonical_paths ( appeared 4 times).
I hope i did a good work.

Changing _canonical variable name to _canonical_paths

---

src/adiar/CMakeLists.txt
src/adiar/internal/io/node_random_access.h
src/adiar/internal/io/node_stream.h
test/adiar/internal/io/test_node_file.cpp

Adds the `node_random_access` class as part of #462 .

Add buffered input stream to provide levelized random access to node files

---

src/adiar/domain.cpp
src/adiar/domain.h
test/adiar/test_domain.cpp

Add `adiar_set_domain(varcount)`

---

src/adiar/domain.cpp
src/adiar/domain.h
src/adiar/internal/util.h
test/adiar/test_domain.cpp

Add generator and iterator overloads to 'adiar_set_domain'

---

src/adiar/internal/algorithms/quantify.h
test/adiar/bdd/test_quantify.cpp

This makes sure the more expensive quantification sweep is not wasted. Assuming the user did not provide non-existing variables, this should only add an O(1) overhead to the start of the quantification algorithm

Transpose input on first existing to-be quantified variable

---

src/adiar/internal/data_structures/levelized_priority_queue.h

Fix LPQ with lookahead of 0 does not track push statistics

---

README.md

Copy of some of Erik's changes before he starts implementing the algorithm(s).

Add dependencies command for Arch Linux

---

docs/Doxyfile.in
docs/index.md

Cleanup of documentation while working on the *docs/internal* branch for #586 .

Docs/Internal (prefix)

---

.github/workflows/static_analysis.yml
CMakeLists.txt
cmake/clang-cxx-dev-tools.cmake
makefile

Clang format

---

src/adiar/bdd/apply.cpp
test/adiar/internal/test_bool_op.cpp

Format 'binary_op' and its tests
