- src/coom/bdd/apply.cpp
- src/coom/bdd/bdd.cpp
- src/coom/bdd/bdd.h
- src/coom/bdd/quantify.cpp
- src/coom/bdd/restrict.cpp
This also fully hides its usage inside the algorithms
> Make __bdd immutable

- .gitignore
- FUTURE_WORK.md
- docs/bdd.md
- src/adiar/CMakeLists.txt
- src/adiar/adiar.h
- src/adiar/bdd/apply.cpp
- src/adiar/bdd/apply.h
- src/adiar/bdd/bdd.h
- src/adiar/bdd/if_then_else.cpp
- src/adiar/bdd/if_then_else.h
- src/adiar/bdd/quantify.cpp
- src/adiar/bdd/restrict.cpp
- src/adiar/data.cpp
- src/adiar/data.h
- src/adiar/homomorphism.cpp
- src/adiar/tuple.h
- test/adiar/bdd/test_if_then_else.cpp
- test/adiar/test_data.cpp
- test/test.cpp
Pull request includes
This includes changes to the Apply algorithm, so of course, we should double-check the code cleanup has not resulted in a slowdown. The following numbers were obtained on _Alice_ with 4GiB of memory available to Adiar and the numbers obtained row-by-row left-to-right.
| `master` | `bdd/if-then-else` |
|------------|-------------------------|
| 708 s     | 686 s                   |
| 696 s     | 692 s                   |
| 702 s     | 686 s                   |
| 700 s     | 680 s                   |
| 696 s     | 681 s                   |
| 698 s     | 682 s                   |
|               |                             |
| 700        | 684,5 s                |
Which alludes to possibly even a 2% performance increase. Definitely, it isn't a performance decrease …
> Implement If-Then-Else algorithm

- src/adiar/data.cpp
This does decrease the maximal size of each layer to 6 TiB of nodes. But, that does seem to be a realistic upper bound on the size of each layer anyway, since you already need 6 TiB above and 6 TiB below to make something so big.
This closes #64 .
> Increase label size to 24 bits

- .github/codecov.yml
The pull request #108 was failing due to moving _covered_ code into a macro, which was not counted anymore. Yet, the lines in all four expansion of the macro were not accounted for. So, since that is a net total decrease in the number of covered lines, that decreased the coverage by 0.03%. It seems wrong to me, that GitHub should outright make it into an error. If it drops by more than 1%, then something bad probably happened, but otherwise, I'd rather judge myself based on the posted report.
> Add settings to omit failure due to removal of covered code

- CMakeLists.txt
- FUTURE_WORK.md
- README.md
- docs/404.md
- docs/_config.yml
- docs/bdd.md
- docs/core.md
- docs/examples.md
- docs/examples/queens.md
- docs/getting_started.md
- docs/index.md
- src/adiar/data.cpp
Covers
- Minor code optimisation by making `equiv_op` into an alias for `xnor_op` which uses fewer bit-operations
- Update `README.md` and remove anything covered in the documentaiton
- Set the _CMake_ version to the soon to-be version of 1.0
- Switch Github Pages theme to [just-the-docs](https://github.com/pmarsceill/just-the-docs)
> Clean up in documentation

- .github/workflows/benchmarks.yml
- .github/workflows/cppcheck.py
- .github/workflows/examples.yml
- .github/workflows/static_analysis.yml
- .github/workflows/test.yml
- src/adiar/adiar.cpp
- src/adiar/bdd/apply.cpp
- src/adiar/bdd/assignment.cpp
- src/adiar/bdd/bdd.cpp
- src/adiar/bdd/bdd.h
- src/adiar/bdd/build.cpp
- src/adiar/bdd/count.cpp
- src/adiar/bdd/count.h
- src/adiar/bdd/evaluate.cpp
- src/adiar/bdd/if_then_else.cpp
- src/adiar/bdd/negate.cpp
- src/adiar/bdd/quantify.cpp
- src/adiar/bdd/restrict.cpp
- src/adiar/data.cpp
- src/adiar/dot.cpp
- src/adiar/file.cpp
- src/adiar/file_stream.cpp
- src/adiar/file_writer.cpp
- src/adiar/file_writer.h
- src/adiar/homomorphism.cpp
- src/adiar/levelized_priority_queue.cpp
- src/adiar/levelized_priority_queue.h
- src/adiar/reduce.cpp
Adds basic code quality control, such as _inclusion guard_ checks and running _CPP Check_. For the latter I had to turn off the `style` checks, since they complain about the implicit one-argument constructors of `bdd` and `__bdd`, though our entire garbage collection works based on these.
As part of these checks I have fixed the following problems
- Inclusion guards in _.cpp_ files should not be there
- Initialization of some variables in the `levelized_priority_queue` private constructor were not in the initialization list.
- `_memory_occupied_by_meta` was not updated correctly in `setup_buckets` for the input being completely without any labels.
> Add CI Static Analsysis: CPP Check, Inclusion Guards

- src/adiar/bdd/build.cpp
- test/adiar/bdd/test_build.cpp
The `lt_sink` variable was of type `ptr_t` not `bool`. So while it was representing the false sink, the number itself was non-zero and hence not falsy.
> Fix bdd_counter returns trivially true on trivially false cases

- .github/workflows/test.yml
- CMakeLists.txt
- docs/getting_started.md
- makefile
- src/adiar/CMakeLists.txt
Clean up and improvements to CMake
- Output build configuration output to console
- Add missing _patch_ number in semantic versioning and _homepage url_
- Make unit tests and examples not included in the build targets when _Adiar_ is included as a submodule (shamelessly stolen from the [lace](https://github.com/trolando/lace/) CMake files).
- Moves the compiler flags completely out of the CMake files and into the hands of the user.
- Remove the need for `set_target_properties(<target> PROPERTIES CXX_STANDARD 17)` when linking to _Adiar_.
> Simplify CMake and improve submodule interaction

- FUTURE_WORK.md
Adds information for _proof logging_ and _hashing_, since they might be interesting projects. This also removes the addition of _zero-suppressed decision diagrams_ since they are added in #128 and finally removes variable reordering, since we may actually look into this ourselves.
> Updating FUTURE_WORK

- src/adiar/internal/pred.cpp
- src/adiar/internal/sorter.h
On release builds the `adiar_invariant` and `adiar_debug` macros are _noops_ and so do nothing with some variables. The #128 pull request introduced in two places functions, where a variable is only mentioned by these macros.
> Fix 'unused variable' warnings

- .github/workflows/benchmark.py
- .github/workflows/benchmark.yml
- .github/workflows/cancel.yml
- .github/workflows/examples.yml
- .github/workflows/system_test.yml
- .github/workflows/unit_test.yml
- README.md
1. Adds new badges and prettifies the prior badges on the Readme.
2. Adds `benchmark.yml` as a new GitHub Action
- Runs a set of benchmarks on both the branch from the pull request and `main`
- Prints a performance report as a comment on the pull request.
- Fails if performance decreases by more than 5%.
3. Fixes the benchmarking system tests also work from forks ( #158 )
Currently, we only run the _14-Queens_ in the _example_ folder. It would be useful to have more benchmarks to use. Can we somehow "run" the `benchmark.py` script on the _benchmarking repository_ instead? This way we can run
- _14_-Queens
- _22_ Tic-Tac-Toe
- _Picotrav_ on _EPFL/Random-Control/voter_. This would currently take more than a day to do a single run, but it should be feasible when we have a critical number of …
> Add performance benchmarking action

- README.md
- docs/index.md
Updates the License notice in the README and in the documentation to not say that TPIE is under GPL 3 but LGPL 3. This does allow the user to use TPIE (and by extension Adiar) as a shared library.
The reason for this misunderstanding is that GitHub extracts the wrong license from the TPIE project, as it looks into 'COPYING.md' rather than the combination with 'COPYNIG.LESSER.md'.
> Fix TPIE license notice is based on GPL rather than LGPL

- CITE.md
- README.md
I will merge this in tomorrow, when we have heard back from TACAS. The _CITE.md_ file should maybe be moved into the _docs/_ folder, such that it is also directly available in the documentation
> Add citations guide and improve Credits section

- src/adiar/bdd/if_then_else.cpp
- src/adiar/data.h
- src/adiar/internal/intercut.h
- src/adiar/internal/product_construction.h
- src/adiar/internal/quantify.h
- test/adiar/bdd/test_quantify.cpp
- test/adiar/zdd/test_expand.cpp
- test/adiar/zdd/test_subset.cpp
In #210 I realized that the `tpie::priority_queue` is not stable - i.e. when two elements are tied, then the oldest element is not necessarily output. It has just been a pure coincidence or due to the stability of merge sort, that I haven't noticed this in the first 700 unit tests.
We don't really care about this in production, as it does provide a slowdown and does not affect correctness of our algorithms. But, for our unit tests - since they are so strictly defining the order - we need the ordering to be total. If we didn't, then orderings will break, when we switch to other sorting algorithms and priority queue implementations, such as the ones mentioned in #98
> Make priority queues totally ordered in debug mode

- src/adiar/internal/product_construction.h
closes #216 
This way we use only one way to do everything everywhere. This reduces the code
complexity and so also the ability to comprehend it
> Use policy pattern in Product Construction helper functions

- .github/workflows/benchmark.py
- .github/workflows/benchmark.yml
- .github/workflows/system_test.yml
This expands the `.github/workflows/benchmark.yml` to not only run *14*-Queens but instead
- **9-Queens** The smallest N, where we don't print the solutions. The largest BDD created is roughly 3 MiB which makes the simple bounds in #98 be ~10 MiB and so easily inside of internal memory.
- **12-Queens** The largest here is 113 MiB which makes some estimates up to ~12 GiB.
- **14-Queens** Here the largest instance itself is larger than the 8 GiB of main memory available.
For *9* and *12* the bottleneck is compilation which takes 2 minutes every time.
> Add benchmarking of smaller instances (closes #246)

- src/adiar/bdd/if_then_else.cpp
- src/adiar/internal/count.h
- src/adiar/internal/intercut.h
- src/adiar/internal/pred.cpp
- src/adiar/internal/pred.h
- src/adiar/internal/product_construction.h
- src/adiar/internal/quantify.h
- src/adiar/internal/substitution.h
- src/adiar/zdd/pred.cpp
On my way to uni I went over the proof for upper bounding based on the number of nodes. The good news are one can almost trivially copy over the proof based on the priority queue to be merely an argument related to the actual (NP-complete) max-cut problem. The bad news are, that we are off-by-one with our current bounds from #98 .
This fixes that.
> Fix: size_based bounds are off-by-one

- src/adiar/bdd/quantify.cpp
- src/adiar/internal/quantify.h
- src/adiar/zdd/project.cpp
That or we need to write down the proof as to why it truly only is internal arcs. Notice, for a node (t1,t2) with a child (t1',F) we turn it into (t1') but that is still an arc (t1,t2) -> (t1') corresponding to the pair of (t1) -> (t1') and (t2) -> (F)
> Fix not counting sinks in quantify 2-level cuts

- src/adiar/bdd/if_then_else.cpp
- src/adiar/internal/cut.h
- src/adiar/internal/product_construction.h
- src/adiar/internal/quantify.h
Closes #296 .
As you can see below there was a slight improvement for the *10-Queens* at *M = 4096* but otherwise nothing happened.
|                                | 128 | 192 | 256 | 512 | 1024 | 1536 | 2048 | 4096 |
|---------------------------|-----|-----|-----|----|-----|-----|-----|----|
| 8                              | 3   | 1 | 0 | 0 | 0 | 0 | 0 | 0 |
| 9                              | 6   | 5 | 5 | 5 | 3 | 1 | 0 | 0 |
| 10                             | 7   | 7 | 7 | 6 | 6 | 6 | 6 | 5 |
| 11                             | 8   | 8 | 8 | 8 | 8 | 7 | 7 | 7 |
| 12                             | 10  | 10 | 9 | 9 | 9 | 9 | 9 | 8 |
|                                | 128 | 192 | 256 | 512 | 1024 | 1536 | 2048 | 4096 |
|---------------------------|-----|-----|-----|----|-----|-----|-----|-- …
> Improve 2-level cut computations

- src/adiar/bdd/if_then_else.cpp
- src/adiar/internal/cut.h
- src/adiar/internal/product_construction.h
- src/adiar/internal/quantify.h
Closes #166 . This should make internal memory used more often, since we fewer times hit the case where the 1/4th of memory given to the per-level priority queue cannot contain as much as the 3/4th given to the levelized priority queue. Why this exactly is a thing in the first place I do not yet fully understand, to be honest.
> Upper bound per-level priority queues based on 1-level cut

- src/adiar/bdd/if_then_else.cpp
- src/adiar/data.h
- src/adiar/file_writer.h
- src/adiar/internal/product_construction.h
- src/adiar/internal/tuple.h
> Remove (irrelevant) use of deprecated 'std::binary_function'

- src/adiar/file_writer.h
> Tighten all four 1-level cuts to use the sound 3/2 upper bound on internal arcs

- src/adiar/statistics.cpp
Changes comparisons in `statistics.cpp` to only be between unsigned integers, fixing some warnings.
> Fix warnings from cnl

- src/adiar/statistics.cpp
> Fix Reduce priority queue statistics are not printed without ADIAR_STATS_EXTRA

- docs/examples/knights_tour.md
- docs/examples/queens.md
- example/examples_common.cpp
- example/knights_tour.cpp
- example/queens.cpp
- src/adiar/builder.h
- test/adiar/test_builder.cpp
Several small bugs / undesired behaviour fixed
- `id` is decremented even if no new node is created
- Crashes on reduction rule 1 collapses everything to a terminal
- Rename `.create()` to `.build()` and `.reset()` to `clear()` to be closer to regular naming schemes.
Furthermore drastically improves documentation
- Doxygen documentation for builder
- Use builders in examples (implementation and documentation) rather than `node_writer`
> Builder Cleanup

- src/adiar/bdd.h
- src/adiar/bdd/count.cpp
- test/adiar/bdd/test_count.cpp
Closes #379 by non-intrusively increasing the default value of `varcount` in `bdd_satcount` if the global domain is set.
> Add global domain to 'bdd_satcount'

- src/adiar/internal/quantify.h
- test/adiar/zdd/test_project.cpp
This just shows how important it is to wrap 'uid' and 'ptr' inside of a class in #397
> Fix 'on_level' for quantification has its arguments swapped

- src/adiar/bdd/negate.cpp
Thank you *CLANG* for the warning.
> Ensure move semantics truly are used for 'bdd_not(bdd &&)'

- src/adiar/bdd/quantify.cpp
- src/adiar/internal/algorithms/nested_sweeping.h
- src/adiar/internal/algorithms/quantify.h
- src/adiar/internal/data_types/request.h
- src/adiar/internal/data_types/tuple.h
- src/adiar/zdd/project.cpp
- test/adiar/bdd/test_quantify.cpp
- test/adiar/internal/algorithms/test_nested_sweeping.cpp
- test/adiar/internal/data_types/test_request.cpp
- test/adiar/zdd/test_project.cpp
Adds optimisation to bail out of running inner sweep, if there are no requests that manipulate the subgraph (thereby postponing a garbage collection).
> Internal/nested sweeping/gc bail

- src/adiar/internal/algorithms/build.h
- src/adiar/internal/algorithms/nested_sweeping.h
- src/adiar/internal/algorithms/quantify.h
- src/adiar/internal/algorithms/reduce.h
- src/adiar/internal/cut.h
- src/adiar/internal/io/node_writer.h
- test/adiar/internal/algorithms/test_nested_sweeping.cpp
- test/adiar/internal/algorithms/test_reduce.cpp
Adds an alternative to `__reduce_level` that skips merging duplicate nodes in the hopes to obtain a higher performance. This seems to potentially give a speed-up of a few percent.
> Nested Sweeping/Fast Reduce

- CMakeLists.txt
> Exclude TPIE and CNL dependency from all targets

- src/adiar/zdd/pred.cpp
> Fix bad index in 'zdd_disjoint' path pruning

- makefile
- src/adiar/bdd.h
- src/adiar/bdd/build.cpp
- src/adiar/bdd/evaluate.cpp
- src/adiar/bdd/restrict.cpp
- src/adiar/domain.cpp
- src/adiar/functional.h
- src/adiar/internal/algorithms/build.h
- src/adiar/internal/algorithms/intercut.h
- src/adiar/internal/algorithms/quantify.h
- src/adiar/internal/util.h
- src/adiar/types.h
- src/adiar/zdd.h
- src/adiar/zdd/build.cpp
- src/adiar/zdd/complement.cpp
- src/adiar/zdd/contains.cpp
- src/adiar/zdd/subset.cpp
- test/adiar/CMakeLists.txt
- test/adiar/bdd/test_build.cpp
- test/adiar/bdd/test_quantify.cpp
- test/adiar/test_domain.cpp
- test/adiar/test_functional.cpp
- test/adiar/zdd/test_build.cpp
- test/adiar/zdd/test_project.cpp
- test/test.cpp
Closes #556 . To do so, I had to change the `generator<...>` to use a `std::optional` to mark the end of the stream. Yet, this makes many things easier such as #458 (as we do not need to introduce an obscure `end()` marker).
> BDD/ `bdd_and` and `bdd_or` with negation

- src/adiar/bdd/bdd_policy.h
- src/adiar/internal/algorithms/pred.cpp
- src/adiar/internal/algorithms/pred.h
- src/adiar/internal/algorithms/prod2.h
- src/adiar/internal/dd.h
- src/adiar/zdd/zdd_policy.h
Turns out it already has been fully replaced, just never removed...
> Remove deprecated 'compute_cofactor'

- docs/example/queens.md
- example/queens.cpp
- src/adiar/bdd.h
- src/adiar/bdd/evaluate.cpp
- src/adiar/functional.h
- src/adiar/internal/algorithms/traverse.h
- src/adiar/zdd.h
- src/adiar/zdd/elem.cpp
- test/adiar/bdd/test_evaluate.cpp
- test/adiar/zdd/test_elem.cpp
**Tasks**
Also various code cleanup for anything traversal related... This makes *src/bdd/evaluate.cpp* and *src/zdd/elem.cpp* eerily similar. But, I have to think a bit more on how truly to merge the common pieces of code.
> BDD/Remove Domain `bdd_satmin` and `bdd_satmax`

- .github/workflows/linux.yml
- .github/workflows/mac.yml
As suggested on the Homebrew repository (Issue 15621). Furthermore, fixed that the Mac (and Linux) build with GCC do not actually use the requested compiler (or version).
This exposes quite a few warnings that should be addressed in the future in some *other* PR.
> Fix MacOS test actions consistently inconsistently breaks

- src/adiar/bdd/bdd.cpp
- src/adiar/zdd/zdd.cpp
Something we noticed when trying to figure out what is going on in our Random Access experiments. Also, the code is nicer...
> Clean up manipulatory assignment operators

- src/adiar/bdd/if_then_else.cpp
- src/adiar/exec_policy.h
- src/adiar/internal/algorithms/count.h
- src/adiar/internal/algorithms/intercut.h
- src/adiar/internal/algorithms/nested_sweeping.h
- src/adiar/internal/algorithms/pred.h
- src/adiar/internal/algorithms/prod2.h
- src/adiar/internal/algorithms/quantify.h
- src/adiar/internal/algorithms/reduce.h
- src/adiar/internal/algorithms/select.h
- src/adiar/internal/data_structures/levelized_priority_queue.h
- test/adiar/bdd/test_quantify.cpp
- test/adiar/internal/algorithms/test_nested_sweeping.cpp
- test/adiar/test_exec_policy.cpp
- test/adiar/zdd/test_project.cpp
Moves heuristic values from Nested Sweeping and Quantification into `exec_policy` (closes #596 ) while also integrating the *fast reduce epsilon* into the Inner Reduce Sweep. We are now almost ready to go searching for a reasonable default value.
> Internal/nested sweeping/exec policy settings

- src/adiar/bdd/quantify.cpp
- src/adiar/internal/algorithms/intercut.h
- src/adiar/internal/algorithms/quantify.h
- src/adiar/internal/data_types/ptr.h
- src/adiar/zdd/project.cpp
In the long run, we would want to go back to the previous(ish) code but where the *is-shortcutting* and *is-irrelevant* predicates are specialised at compile-time as described in #162 .
> Preliminary hack to approximate #162 optimisation inside of Quantify

- src/adiar/exec_policy.h
- src/adiar/internal/algorithms/quantify.h
- test/adiar/bdd/test_quantify.cpp
- test/adiar/zdd/test_project.cpp
Add the "shallow variables" heuristic anew to revert the slowdown introduced in #608 .
> WIP: Readd shallow variables heuristic

- src/adiar/internal/algorithms/quantify.h
This is a slightly more (and also less) sophisticated version of the terminal arcs heuristic we had in earlier. Instead of stopping the partial quantification when there are few arcs, we (1) weigh it based on collapsing arcs and (2) compute a maximum number of sweeps based on an exponential function.
> Readd terminal arcs heuristic

- src/adiar/exec_policy.h
- src/adiar/internal/algorithms/quantify.h
Disables Partial Sweeping and Repeated Transposition by default. Furthermore, it also removes the Terminal Count heuristic since it did not seem to be working or explainable.
> Internal/quantify/terminal heuristic  (3)

- src/adiar/internal/algorithms/quantify.h
- test/adiar/bdd/test_quantify.cpp
- test/adiar/zdd/test_project.cpp
Closes #652 ; the code is feels slightly hacky/ugly. But, it seems more a sign of a deeper problem that ought to be fixed.
> Add terminal pruning for initial transposition sweep

- .github/workflows/benchmark.yml
> Fix deprecated usage of GitHub action 'set-output'

- src/adiar/bdd.h
- src/adiar/bdd/quantify.cpp
- src/adiar/bdd/relprod.cpp
- src/adiar/internal/algorithms/quantify.h
- src/adiar/zdd.h
- src/adiar/zdd/project.cpp
- test/adiar/bdd/test_quantify.cpp
- test/adiar/bdd/test_relprod.cpp
- test/adiar/zdd/test_change.cpp
- test/adiar/zdd/test_project.cpp
Optimisation from #502 : Skips the *transposition step* of the `bdd_exists` by using the unreduced (and already transposed) output of `bdd_and`.
> BDD/RelProd/Apply Transpose

- src/adiar/bdd/apply.cpp
- src/adiar/bdd/bdd.h
- src/adiar/bdd/relprod.cpp
- src/adiar/internal/algorithms/prod2.h
- src/adiar/zdd/binop.cpp
- test/adiar/bdd/test_relprod.cpp
Optimisation from #502 : Integrates the *pruning* optimisation directly within the `bdd_and` transposition sweep.
> BDD/RelProd/Quantification Pruning

- CHANGELOG.md
- src/adiar/internal/algorithms/nested_sweeping.h
- src/adiar/internal/io/levelized_file_stream.h
- test/adiar/bdd/test_quantify.cpp
- test/adiar/internal/algorithms/test_nested_sweeping.cpp
- test/adiar/zdd/test_project.cpp
> Internal/nested sweep/2 level cuts

- src/adiar/adiar.cpp
The TPIE_log*.txt file can within a single day get very large, e.g. 3.5+ TiB large. Yet, it is very seldomly (if ever) we need it - especially not in production.
> Only enable TPIE's logging while in Debug

- src/adiar/adiar.cpp
This avoids an additional directory named `TPIE_<date>_<…>` at the default tmp path.
About a year ago, when executing benchmarks in a scripted way, I ran into the problem that the BDDs produced by Adiar filled up the entire disk. Because of that, the benchmarking process crashed and left the files there, so my benchmark runner script was not even able to create new log files for the upcoming benchmarks. That was when I started to use the `-T` option in BDD benchmark to make Adiar write to a location I previously created using Python’s `tempfile.TemporaryDirectory()`, so I could be sure that would be cleaned even upon timeouts and crashes.
However, that fix seemed to be ineffective, Adiar still created directories named `TPIE_<date>_<…>` in my `/tmp` folder. So I added two additional lines …
> Set `tpie::tempname` before calling `tpie_init()`

- .github/workflows/benchmark.yml
- .github/workflows/coverage.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/static_analysis.yml
- .github/workflows/system_test.yml
Continuous Integration is broken due to it not being up to date.
> Fix Continuous Integration
